//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hama.WinApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hama.WinApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage bo_security_permission_action {
            get {
                object obj = ResourceManager.GetObject("bo_security_permission_action", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HybridWinApp {
            get {
                object obj = ResourceManager.GetObject("HybridWinApp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HybridWinApp_G {
            get {
                object obj = ResourceManager.GetObject("HybridWinApp-G", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HybridWinApp_Y {
            get {
                object obj = ResourceManager.GetObject("HybridWinApp-Y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctypehtml&gt;&lt;html lang=en&gt;&lt;style&gt;*{margin:0;padding:0;box-sizing:border-box}body{display:flex;justify-content:center;align-items:center;min-height:100vh;background:#f4f4f4}section{position:absolute;width:100vw;height:100vh;display:flex;justify-content:center;align-items:center;gap:2px;flex-wrap:wrap;overflow:hidden}section::before{content:&apos;&apos;;position:absolute;width:100%;height:100%;background:linear-gradient(#f4f4f4,#00b294,#f4f4f4);animation:animate 5s linear infinite}@keyframes animate{0%{transform:tran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoginHtmlGreen {
            get {
                return ResourceManager.GetString("LoginHtmlGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctypehtml&gt;&lt;html lang=en&gt;&lt;style&gt;*{margin:0;padding:0;box-sizing:border-box}body{display:flex;justify-content:center;align-items:center;min-height:100vh;background:#2e2e2e}section{position:absolute;width:100vw;height:100vh;display:flex;justify-content:center;align-items:center;gap:2px;flex-wrap:wrap;overflow:hidden}section::before{content:&apos;&apos;;position:absolute;width:100%;height:100%;background:linear-gradient(#2e2e2e,#ffc21a,#2e2e2e);animation:animate 5s linear infinite}@keyframes animate{0%{transform:tran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoginHtmlYellow {
            get {
                return ResourceManager.GetString("LoginHtmlYellow", resourceCulture);
            }
        }
    }
}
